### ISSUE TITLE
Bugs review

### ISSUE THREAD

**Issue by CapriLucas** [crisszkutnik/sortingvisualizer-v2#1]
¿Buenas como andas @crisszkutnik? Estaba revisando este proyecto y me encontré con dos bugs que deberían ser relativamente sencillos de resolver y quedarían, a mi entender, muy bien.
1 - Bug de poder ejecutar un sort mientras ya hay uno en proceso. Lo que se me ocurre es poner el botón "SORT" como disabled hasta terminarlo. O quizá resetear el sort una vez presionado el botón
2 - Menos importante: Cuando modificas cualquiera de los inputs de tipo range del header (como los diferentes números tiene distintos tamaños) genera un movimiento en todos los elementos contiguos del header

**Comment by GuidoDipietro** [comment]
wtf cómo llegaste acá

**Comment by CapriLucas** [comment]
Jaja en la sección de explore de GitHub me apareció. Debe ser xq pertenecemos a alguna misma organización supongo

**Comment by crisszkutnik** [comment]
Bueno tarde pero seguro te respondo el issue jajajaja

Este proyecto quedo re olvidado no te voy a mentir pero ahora que me marcaste esos bugs le voy a dar un poquito de amor

Gracias por tomarte el tiempo, no te voy a menitr, no esperaba que nadie vea esto, ni mucho menos se ponga a buscarle bugs jajaja
